import operator
import random
import colorsys
import pylab
import getopt
import sys
import os
import coverage
import math

from .treemap import Treemap
from .coverageutils import CoveredCode, CoveredModule


def example():    
    """
    Treemap demo!
    
    This shows an example of creating a treemap  of nested tuples, random colours.
    Node size is sum of leaf elements.
    """ 
    
    size_cache = {}
    
    def size(thing):
        """sum size of child nodes"""
        if isinstance(thing, int) or isinstance(thing, float):
            return thing
        if thing in size_cache:
            return size_cache[thing]
        else:
            size_cache[thing] = reduce(operator.add, [size(x) for x in thing])
            return size_cache[thing]
    
    def random_color(thing):
        """just return a random color"""
        return colorsys.hsv_to_rgb(random.random(), 0.5, 1)
    
    tree = ((5, (3, 5, 2, (0.1, 0.1, 0.6), 1)), 4, 
            (5, 2, (2, 3, (3, 2, (2, 5, 2), 2)), 
             (3, 3)), (3, 2, (0.2, 0.2, 0.2)))
    

    tm = Treemap(tree, size, random_color)    
    pylab.show()
    
    
def test_coverage():
    """Treemap visualisation of coverage information.
    
    This script will visually display a coverage file generated by Ned
    Batchelders statment coverage module, coverage.py (available from 
    http://www.nedbatchelder.com/code/modules/coverage.html).  Each node
    in the treemap is a python module with size is given by the number 
    of lines of code and colour of the by the coverage. Red is no coverage, 
    green is full coverage.  Mouse hovering will show the name of the file.
    
    The script automatically looks in the current directory for a 
    .coverage file to display.  Else you can specify a file using the first
    argument.  e.g.
    
        treemap_coverage /path/to/.coverage
    
    You can include or exclude modules using --include or --exclude.  For 
    example, to exclude all files in the treemap package:
    
        treemap_coverage --exclude treemap /path/to/.coverage
    """
    try:
        opts, args = getopt.getopt(sys.argv[1:], "hi:ve:v", ["help", "include=", "exclude=", "img="])
    except getopt.GetoptError:
        print(test_coverage.__doc__)
        sys.exit(2)
        
    coverage_file = os.environ.get('COVERAGE_FILE') or ".coverage"
    includes = []
    excludes = []
    output_img = None
    
    for o, a in opts:
        if o in ("-h", "--help"):
            print(test_coverage.__doc__)
            sys.exit()
        if o in ("-i", "--include"):
            includes = a.split(',')
        if o in ("-e", "--exclude"):
            excludes = a.split(',')
        if o in ("--img"):
            output_img = a
            
    if len(args) > 0:
        coverage_file = args[0]
    
    if not os.path.exists(coverage_file):
        print("%s: file does not exist (try --help)" % coverage_file)
        sys.exit(2)

    # API at https://coverage.readthedocs.io/en/coverage-3.5.3/api.html
    coverage_obj = coverage.coverage(data_file=coverage_file)
    coverage_obj.load()

    wanted_files = coverage_obj.data.measured_files()
    
    if includes:
        wanted_files = filter(
            lambda file_name: [file_name for substr in includes if substr in file_name],
            wanted_files
        )
    if excludes:
        wanted_files = filter(
            lambda file_name: [file_name for substr in excludes if substr not in file_name],
            wanted_files
        )
    
    code = CoveredCode(wanted_files, coverage=coverage_obj)
    root = code.root_module()
    
    Treemap( root,  code.size, code.color, iter_method=code.child_modules )
    if not output_img:
        pylab.show()
    else:
        root_node_size = len(code.child_modules(root))
        dpi = math.log(root_node_size) * 300
        print("Using image DPI: {} (root size={})".format(dpi, root_node_size))
        pylab.savefig(
            output_img,
            dpi=dpi
        )
        print("Written image file to: {}".format(output_img))
    
